### ISSUE TITLE
Simplify GameLoop usage

### ISSUE THREAD

**Issue by ryukinix** [NewayPix/hazard-memory#30]
# DEFINITION OF DONE

- [x] It should not necessary add `using GameLoop::GameLoop`
- [x] It should not necessary declare class definition of Game with inheritance of GameLoop
- [x] It should update all current examples with the new usage 
- [x] It should only need to define event, update and render*.
- [ ] ~~It should possible define start and stop too.~~ (wontfix)
- [x] It should refactor GameLoop definition with proper usage of private and public method: some of them are public without need.
- [x] It should rename `render` method to `draw`
# Questions

- We should rename render to draw? Why?

**Comment by rafaelcn** [comment]
Answering your question about `draw` and `render`. I think the latter implies a technique used when drawing onto the screen/frame buffer and the first one doesn't imply anything other than the engine drawing, using whatever technique is available.

**Comment by rafaelcn** [comment]
What's the definition of DONE?

**Comment by ryukinix** [comment]
[Definition of Done](https://www.productplan.com/agile-definition-of-done/#:~:text=The%20Definition%20of%20Done%20is,progress%E2%80%9D%20to%20%E2%80%9Cdone.%E2%80%9D) it's a common term defined on Agile disciplines to keep the task expectation aligned. When all the requisites are completed, it's done: the task/issue can be closed.

**Comment by ryukinix** [comment]
> Answering your question about `draw` and `render`. I think the latter implies a technique used when drawing onto the screen/frame buffer and the first one doesn't imply anything other than the engine drawing, using whatever technique is available.

Given that explanation, maybe GameLoop::draw it's a more proper term? Disclosure: that is a @wesleycsj suggestion.

**Comment by wesleycsj** [comment]
I agree. Rendering and Rastering are more internal concepts, and `draw` is a more general word. Plus, it's short to type.

**Comment by ryukinix** [comment]
So we are renaming render to draw!

**Comment by ryukinix** [comment]
Considering our current loop, what about `event`? Should we rename it too? It's now or never.

https://github.com/NewayPix/hazard-memory/blob/8dbe7f5fd0af52d19cfb277e0251e722991ac5b7/src/GameLoop.hpp#L76-L83

**Comment by wesleycsj** [comment]
I think we should, but thinking better right now, we need to maintain this event loop to process all events, including window signals and SDL internals, and inside this we can derive others events more specific , like key press, key up, key down..etc.

**Comment by ryukinix** [comment]
Ok, so I'll maintain it for now.
