### ISSUE TITLE
Define C++ style guideline for the project

### ISSUE THREAD

**Issue by ryukinix** [NewayPix/hazard-memory#31]
My recommendation: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md

A linter it would be good, do you know anyone @rafaelcn ?

**Comment by ryukinix** [comment]
Currently we should use that naming convention:

```
class/struct/enum/union: ClassName (CamelCase)
variable/attribute: variable_name, field_name (snake_case)
method/function: method_name, func_name (snake_case)
macro/pre-processor: TRALALA_H, SCREEN_WIDHT (SNAKE_CASE)
```

**Comment by rafaelcn** [comment]
Nop, that's the best I've heard of. I would endorse those rules to be applied here.

**Comment by ryukinix** [comment]
So it's decided, that is it.
