### ISSUE TITLE
Implement Circle draw function and remove sdl_gfx dependency

### ISSUE THREAD

**Issue by ryukinix** [NewayPix/hazard-memory#33]
# Definition of Done

- [ ] Create a mechanism to draw a circle, you can include a method as method of `Circle`
- [ ] Refactor breakout and square-platform to render circles with the new mechanism
- [ ] Remove sdl_gfx from CI config

**Comment by wesleycsj** [comment]
There is not point on this. We will give up from a complete and probably optimized library that will be needed later just to do manually a Bresenham's Circle Algorithm? I vote to keep sdl_gfx to use primitives for Circle, Rectangle(maybe Triangle?) class. Anyway it could be used to draw GUI engine components in the future.

**Comment by ryukinix** [comment]
>  I vote to keep sdl_gfx to use primitives for Circle, Rectangle(maybe Triangle?) class.

Understandable. Keep in mind that the capability to draw Rectangle comes up with the main SDL library, it's necessary sdl_gfx for that. We only use `sdl_gfx` for draw circles currently. I think one good option in that case, for start, it's just create a abstraction to render Circles through sdl_gfx. If we need remove `sdl_gfx` it would make simpler later.

It seems that sdl_gfx have some problems:

- https://stackoverflow.com/questions/39541447/rendering-with-sdl-gfx-is-so-slow-any-alternative
- https://directory.fsf.org/wiki/SDL2_gfx

**Comment by ryukinix** [comment]
Just to share, I found something useful on SDL2_gfx that we implemented by ourself:

- https://www.ferzkopp.net/Software/SDL_gfx-2.0/Docs/html/_s_d_l__framerate_8h.html

It seems that worked the same way we implemented, but they provided already a fps counter (which we do not provide in the engine yet). Maybe we should try to use and see what happens.

**Comment by ryukinix** [comment]
Nice, good. Finally we agree that sdl_gfx. I'm closing this.
